---
- name: Update complete
  apt:
    name: "*"
    state: latest
  notify: "Install packages"
  when: ansible_os_family == "Debian" and ansible_distribution_version == '11'

- name: Update Windows
  ansible.windows.win_updates:
    category_names: "{{ item }}"
    reboot: yes
    state: downloaded
  when: ansible_os_family == "Windows"
  with_items:
  - "{{ update_types }}"