---
- name: Update complete | Debian
  apt:
    name: "*"
    state: latest
  notify: "Install packages | Debian"
  when: ansible_os_family == "Debian" and ansible_distribution_version == '11'

- name: Update complete | RedHat equals 6
  yum:
    name: "*"
    state: latest
  notify: "Install packages | RedHat equals 6"
  when: ansible_os_family == "Redhat" and ansible_distribution_version >= '6' and ansible_distribution_version < '7'

- name: Update complete | RedHat equals 7
  yum:
    name: "*"
    state: latest
  notify: "Install packages | RedHat equals 7"
  when: ansible_os_family == "Redhat" and ansible_distribution_version >= '7' and ansible_distribution_version < '8'

- name: Update complete | RedHat equals 8
  yum:
    name: "*"
    state: latest
  notify: "Install packages | RedHat equals 8"
  when: ansible_os_family == "Redhat" and ansible_distribution_version >= '8' and ansible_distribution_version < '9'

- name: Update complete | RedHat equals 9
  yum:
    name: "*"
    state: latest
  notify: "Install packages | RedHat equals 9"
  when: ansible_os_family == "Redhat" and ansible_distribution_version >= '9'

- name: Update pip and setuptools | Debian
  pip:
    name: "{{ item }}"
    state: latest
  when: ansible_os_family == "Debian" and ansible_distribution_version == '11'
  with_items:
  - "{{ pip_updates }}"
  notify: "OCI python CLI | Debian"

- name: Update pip and setuptools | Redhat equals 6
  pip:
    name: "{{ item }}"
    state: latest
  when: ansible_os_family == "Redhat" and ansible_distribution_version >= '6' and ansible_distribution_version < '7'
  with_items:
  - "{{ pip_updates }}"
  notify: "OCI python CLI | Redhat equals 6"

- name: Update pip and setuptools | Redhat equals 7
  pip:
    name: "{{ item }}"
    state: latest
  when: ansible_os_family == "Redhat" and ansible_distribution_version >= '7' and ansible_distribution_version < '8'
  with_items:
  - "{{ pip_updates }}"
  notify: "OCI python CLI | Redhat equals 7"

- name: Update pip and setuptools | Redhat equals 8
  pip:
    name: "{{ item }}"
    state: latest
  when: ansible_os_family == "Redhat" and ansible_distribution_version >= '8' and ansible_distribution_version < '9'
  with_items:
  - "{{ pip_updates }}"
  notify: "OCI python CLI | Redhat equals 8"

- name: Update pip and setuptools | Redhat equals 9
  pip:
    name: "{{ item }}"
    state: latest
  when: ansible_os_family == "Redhat" and ansible_distribution_version >= '9'
  with_items:
  - "{{ pip_updates }}"
  notify: "OCI python CLI | Redhat equals 9"

- name: Update Windows | Windows
  ansible.windows.win_updates:
    category_names: "{{ item }}"
    reboot: yes
    state: downloaded
  when: ansible_os_family == "Windows"
  with_items:
  - "{{ update_types }}"