---
- name: Install packages
  apt:
    name: "{{ item }}"
    state: latest
  when: ansible_os_family == 'Debian' and ansible_distribution_version == '11'
  with_items: 
  - packages

- name: OCI python CLI
  pip:
    name: oci-cli
    state: latest
  when: ansible_os_family == 'Debian' and ansible_distribution_version == '11'