---
- name: Install packages | Debian
  become: true
  apt:
    name: "{{ item }}"
    state: latest
  when: ansible_os_family == 'Debian' and ansible_distribution_version == '11'
  with_items: 
  - packages

- name: Install packages | RedHat equals 6
  become: true
  apt:
    name: "{{ item }}"
    state: latest
  when: ansible_os_family == "Redhat" and ansible_distribution_version >= '6' and ansible_distribution_version < '7'
  with_items: 
  - packages

- name: Install packages | RedHat equals 7
  become: true
  apt:
    name: "{{ item }}"
    state: latest
  when: ansible_os_family == "Redhat" and ansible_distribution_version >= '7' and ansible_distribution_version < '8'
  with_items: 
  - packages

- name: Install packages | RedHat equals 8
  become: true
  apt:
    name: "{{ item }}"
    state: latest
  when: ansible_os_family == "Redhat" and ansible_distribution_version >= '8' and ansible_distribution_version < '9'
  with_items: 
  - packages

- name: Install packages | RedHat equals 9
  become: true
  apt:
    name: "{{ item }}"
    state: latest
  when: ansible_os_family == "Redhat" and ansible_distribution_version >= '9'
  with_items: 
  - packages

- name: OCI python CLI | Debian
  become: true
  pip:
    name: oci-cli
    state: latest
  when: ansible_os_family == 'Debian' and ansible_distribution_version == '11'

- name: OCI python CLI | RedHat equals 6
  become: true
  pip:
    name: oci-cli
    state: latest
  when: ansible_os_family == "Redhat" and ansible_distribution_version >= '6' and ansible_distribution_version < '7'

- name: OCI python CLI | RedHat equals 7
  become: true
  pip:
    name: oci-cli
    state: latest
  when: ansible_os_family == "Redhat" and ansible_distribution_version >= '7' and ansible_distribution_version < '8'

- name: OCI python CLI | RedHat equals 8
  become: true
  pip:
    name: oci-cli
    state: latest
  when: ansible_os_family == "Redhat" and ansible_distribution_version >= '8' and ansible_distribution_version < '9'

- name: OCI python CLI | RedHat equals 9
  become: true
  pip:
    name: oci-cli
    state: latest
  when: ansible_os_family == "Redhat" and ansible_distribution_version >= '9'

- name: Install Win packages
  ansible.windows.win_get_url:
    url: "{{ item }}"
    dest: C:\Users\rvann\Downloads
    force: no
  when: ansible_os_family == "Windows"